use_frameworks!

platform :ios, '12.0'

target 'WebRTCForAyame_Example' do
  pod 'WebRTCForAyame', :path => '../'
  pod 'ReachabilitySwift'
  pod 'SocketRocket'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'DJIWidget' , :git => 'https://gitee.com/TaylorZhang/DJIWidget.git'
  
  target 'WebRTCForAyame_Tests' do
    inherit! :search_paths

    
  end
end


#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    flutter_additional_ios_build_settings(target)
#      target.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = ‘12.0’
#      end
#    end
#end
