use_frameworks!

platform :ios, '12.0'

target 'WebRTCForAyame_Example' do
  pod 'WebRTCForAyame', :path => '../'
  pod 'ReachabilitySwift'
  pod 'SocketRocket'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'ZSGCDTimer' , :git => 'https://gitee.com/TaylorZhang/ZSGCDTimer.git'
  pod 'DJIWidget' , :git => 'https://gitee.com/TaylorZhang/DJIWidget.git'
  
  target 'WebRTCForAyame_Tests' do
    inherit! :search_paths

    
  end
end
